version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.7
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      AWS_ACCESS_KEY: $AWS_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_SECRET_KEY
      AWS_REGION: 'eu-central-1'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-aws'
      ENABLE_MODULES: 'text2vec-aws,img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ADMIN_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ADMIN_PASSWORD
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  weaviate-data:
